<?php
/**
 * Created by PhpStorm.
 * User: TakayamaAren
 * Date: 12/23/2017
 * Time: 1:46 PM
 */

namespace app\admin\controller;


use app\common\controller\BaseController;
use app\common\model\UserModel;

class Staff extends BaseAdminController
{
    public function getSideIndex()
    {
        return "staff";
    }

    protected function _initialize()
    {
        parent::_initialize();
        if (!$this->user->superuser) {
            $this->error("当前用户不是超级用户");
        }
    }

    public function index()
    {
        $staffList = (new UserModel())
            ->where("staff", "=", true)
            ->select();
        $this->assign("staffList", $staffList);

        return parent::index(); // TODO: Change the autogenerated stub
    }

    public function destaff()
    {
        $uid = $this->request->param("uid");
        if ($uid == $this->user->id){
            $this->error("不能自己删除自己");
        }
        $model = UserModel::get($uid);
        $model->staff = false;
        $model->save();
        $this->redirect("/admin/staff");
    }

    public function bestaff()
    {
        $username = $this->request->post("username");

        $model = new UserModel();
        $model->save(
            ["staff" =>true],["username"=>$username]
        );
        $this->redirect("/admin/staff");
    }

}