<?php
/**
 * Created by PhpStorm.
 * User: TakayamaAren
 * Date: 12/20/2017
 * Time: 6:15 PM
 */

namespace app\user\controller;


class Balance extends BaseUserController
{
    public function index()
    {
        return parent::index(); // TODO: Change the autogenerated stub
    }
}